<?php

use Illuminate\Database\Seeder;

class InmueblesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('inmuebles')->insert([
        	'id'		=> 1,
        	'tipo_id' => 1,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 2,
        	'tipo_id' => 2,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 3,
        	'tipo_id' => 3,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 4,
        	'tipo_id' => 1,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 5,
        	'tipo_id' => 1,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 6,
        	'tipo_id' => 2,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 7,
        	'tipo_id' => 2,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        DB::table('inmuebles')->insert([
        	'id'		=> 8,
        	'tipo_id' => 1,
        	'categoria_id' => 1,
        	'obranueva' => 1,
            'agencia_id' => 1
            'promocion_id' => 1,
        	'adjbancaria' => 1,
        	'entidad_id' => 1,
        	'fecha_alta' => '2017-04-20',
        	'estado' => 'disponible',
        	'periodicidad' => 'Indiferente',
        	'usuario_id' => 1,
        	'superficie' => 12,
        	'modalidad_id' => 23,
        	'municipio_id' => 1,
        	'zona' =>'centro',
        	'codigo_postal' => '1234',
        	'pais_id' => 1,
        	'via_id' => 2,
        	'calle' => '432',
        	'numero' => '345',
        	'piso' => 'Sótano',
        	'escalera' => '2',
        	'puerta' => '3',
        	'mostrardireccion' => 1,
        	'moneda' => 'EUR - Euro',
        	'idioma_id' => 1,
        	'descripcion_corta' => 'bla bla bla',
        	'descripcion_extendida' => 'bla bla bla bla',
        	'idioma_id2' => 0
        	]);
        
    }
}
